call az provider register -n microsoft.compute
call az provider register -n microsoft.network
call az provider register -n microsoft.dbforpostgresql
call az provider register -n microsoft.containerservice
call az provider register -n microsoft.dbformysql
call az provider register -n microsoft.storage
call az provider register -n microsoft.recoveryservices
call az provider register -n microsoft.sql
call az provider register -n microsoft.resources
call az provider register -n microsoft.netapp
call az provider register -n cloudsimple.privatecloudiaas
call az provider register -n microsoft.insights
call az provider register -n microsoft.avs
call az provider register -n microsoft.cache
call az provider register -n microsoft.cdn
call az provider register -n microsoft.search
call az provider register -n microsoft.security
call az provider register -n microsoft.cognitiveservices
call az provider register -n microsoft.servicefabricmesh
call az provider register -n microsoft.documentdb
call az provider register -n microsoft.apimanagement
call az provider register -n microsoft.web
call az provider register -n microsoft.hybridnetwork
call az provider register -n microsoft.containerregistry
call az provider register -n microsoft.containerinstance
call az provider register -n microsoft.networkcloud
call az provider register -n microsoft.eventgrid
call az provider register -n microsoft.kusto
call az provider register -n microsoft.autonomousdevelopmentplatform
call az provider register -n microsoft.batch
call az provider register -n microsoft.keyvault
call az provider register -n microsoft.operationalinsights
call az provider register -n microsoft.apisecurity
call az provider register -n microsoft.app
call az provider register -n microsoft.automanage
call az provider register -n microsoft.databox
call az provider register -n microsoft.virtualmachineimages
call az provider register -n microsoft.mission
call az provider register -n microsoft.guestconfiguration
call az provider register -n microsoft.streamanalytics
call az provider register -n microsoft.devcenter
call az provider register -n private.autonomousdevelopmentplatform
call az provider register -n microsoft.automation
call az provider register -n microsoft.datalakeanalytics
call az provider register -n microsoft.dbformariadb
call az provider register -n microsoft.powerbidedicated
call az provider register -n microsoft.advisor
call az provider register -n microsoft.appconfiguration
call az provider register -n microsoft.healthcareapis
call az provider register -n microsoft.devtestlab
call az provider register -n microsoft.analysisservices
call az provider register -n microsoft.deviceupdate
call az provider register -n microsoft.hdinsight
call az provider register -n microsoft.powerbi
call az provider register -n microsoft.dataprotection
call az provider register -n microsoft.datacollaboration
call az provider register -n microsoft.machinelearningservices
call az provider register -n microsoft.hybridcompute
call az provider register -n microsoft.windows365
call az provider register -n microsoft.operationsmanagement
call az provider register -n microsoft.maps
call az provider register -n microsoft.playfab
call az provider register -n microsoft.workloads
call az provider register -n microsoft.signalrservice
call az provider register -n microsoft.logic
call az provider register -n microsoft.changeanalysis
call az provider register -n microsoft.redhatopenshift
call az provider register -n microsoft.kubernetesconfiguration
call az provider register -n microsoft.policyinsights
call az provider register -n microsoft.expresspod
call az provider register -n microsoft.azurearcdata
call az provider register -n microsoft.confluent
call az provider register -n microsoft.edgemarketplace
call az provider register -n microsoft.d365customerinsights
call az provider register -n microsoft.peering
call az provider register -n microsoft.impact
call az provider register -n microsoft.databricks
call az provider register -n microsoft.azuresphere
call az provider register -n microsoft.hybridconnectivity
call az provider register -n microsoft.maintenance
call az provider register -n microsoft.communication
call az provider register -n microsoft.cloudes
call az provider register -n microsoft.storsimple
call az provider register -n microsoft.modsimworkbench
call az provider register -n microsoft.aisupercomputer
call az provider register -n paloaltonetworks.cloudngfw
call az provider register -n microsoft.resourcehealth
call az provider register -n microsoft.desktopvirtualization
call az provider register -n qumulo.qaas
call az provider register -n microsoft.securitydetonation
call az provider register -n microsoft.iotcentral
call az provider register -n microsoft.awsconnector
call az provider register -n microsoft.azureimagetestingforlinux
call az provider register -n microsoft.hardwaresecuritymodules
call az provider register -n microsoft.elasticsan
call az provider register -n microsoft.notebooks
call az provider register -n microsoft.industrydatalifecycle
call az provider register -n microsoft.azurespheregen2
call az provider register -n microsoft.customproviders
call az provider register -n microsoft.confidentialledger
call az provider register -n microsoft.migrate
call az provider register -n purestorage.block
call az provider register -n nginx.nginxplus
call az provider register -n microsoft.notificationhubs
call az provider register -n microsoft.sqlvirtualmachine
call az provider register -n microsoft.singularity
call az provider register -n microsoft.devspaces
call az provider register -n microsoft.storageinsights
call az provider register -n microsoft.scom
call az provider register -n microsoft.powerplatform
call az provider register -n microsoft.capacity
call az provider register -n microsoft.standbypool
call az provider register -n microsoft.alertsmanagement
call az provider register -n microsoft.machinelearningexperimentation
call az provider register -n microsoft.azurescan
call az provider register -n microsoft.extendedlocation
call az provider register -n microsoft.programmableconnectivity
call az provider register -n microsoft.synapse
call az provider register -n microsoft.ai
call az provider register -n microsoft.microsoft
call az provider register -n microsoft.saas
call az provider register -n microsoft.azuredatatransfer
call az provider register -n microsoft.kubernetes
call az provider register -n microsoft.portal
call az provider register -n microsoft.connectedenvironment
call az provider register -n microsoft.domainregistration
call az provider register -n microsoft.devopsinfrastructure
call az provider register -n private.altstest
call az provider register -n private.modsimworkbench
call az provider register -n microsoft.aadiam
call az provider register -n microsoft.dataexchange
call az provider register -n microsoft.databoxedge
call az provider register -n microsoft.monitor
call az provider register -n qumulo.storage
call az provider register -n providers.test
call az provider register -n test.shoebox
call az provider register -n microsoft.machinelearningcompute
call az provider register -n microsoft.labservices
call az provider register -n newrelic.observability
call az provider register -n microsoft.classicinfrastructuremigrate
call az provider register -n microsoft.importexport
call az provider register -n microsoft.iotsecurity
call az provider register -n microsoft.agfoodplatform
call az provider register -n microsoft.m365securityandcompliance
call az provider register -n microsoft.servicefabric
call az provider register -n microsoft.baremetal
call az provider register -n microsoft.apicenter
call az provider register -n microsoft.quantum
call az provider register -n microsoft.secretmanagementsampleprovider
call az provider register -n microsoft.resourceconnector
call az provider register -n microsoft.terraformoss
call az provider register -n microsoft.edgezones
call az provider register -n microsoft.visualstudio
call az provider register -n microsoft.signalr
call az provider register -n microsoft.projectbabylon
call az provider register -n microsoft.devices
call az provider register -n microsoft.storagemover
call az provider register -n microsoft.serviceshub
call az provider register -n microsoft.diagnostics
call az provider register -n microsoft.datafactory
call az provider register -n private.securitycopilot
call az provider register -n microsoft.computeschedule
call az provider register -n microsoft.healthdataaiservices
call az provider register -n microsoft.anybuild
call az provider register -n microsoft.azurestackhci
call az provider register -n microsoft.securitygraph
call az provider register -n microsoft.datalakestore
call az provider register -n microsoft.fluidrelay
call az provider register -n microsoft.cascade
call az provider register -n microsoft.securitydevops
call az provider register -n microsoft.datadog
call az provider register -n microsoft.storagepool
call az provider register -n microsoft.securityinsights
call az provider register -n microsoft.datareplication
call az provider register -n microsoft.mobilenetwork
call az provider register -n microsoft.bing
call az provider register -n microsoft.saashub
call az provider register -n microsoft.eventhub
call az provider register -n microsoft.professionalservice
call az provider register -n microsoft.serialconsole
call az provider register -n microsoft.portalservices
call az provider register -n microsoft.appassessment
call az provider register -n microsoft.relay
call az provider register -n microsoft.quota
call az provider register -n microsoft.connectedopenstack
call az provider register -n microsoft.providerhub
call az provider register -n microsoft.m365
call az provider register -n microsoft.hybridcontainerservice
call az provider register -n microsoft.backupsolutions
call az provider register -n solarwinds.observability
call az provider register -n microsoft.operatorvoicemail